apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
      version: green
  template:
    metadata:
      labels:
        app: order-service
        version: green
    spec:
      containers:
      - name: order-service
        image: us-central1-docker.pkg.dev/csc-8113/bookstore-repo/order-service:v3
        ports:
        - containerPort: 5003
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-green
spec:
  selector:
    app: order-service
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
  type: ClusterIP
