apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: blue
  template:
    metadata:
      labels:
        app: user-service
        version: blue
    spec:
      containers:
      - name: user-service
        image: us-central1-docker.pkg.dev/csc-8113/bookstore-repo/user-service:v3
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_URI
        resources:
          limits:
            cpu: "50m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5002
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-blue
spec:
  selector:
    app: user-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP
